"""Initial migration

Revision ID: 5f9f3f9af716
Revises: 
Create Date: 2024-09-24 12:41:02.008449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9f3f9af716'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_data', sa.Column('weather_station_id', sa.Integer(), nullable=False))
    op.add_column('forecast_data', sa.Column('forecast_date', sa.DateTime(), nullable=False))
    op.add_column('forecast_data', sa.Column('forecast', sa.String(length=255), nullable=False))
    op.add_column('forecast_data', sa.Column('forecast_temp', sa.Float(), nullable=False))
    op.add_column('forecast_data', sa.Column('forecast_humidity', sa.Float(), nullable=False))
    op.create_index(op.f('ix_forecast_data_id'), 'forecast_data', ['id'], unique=False)
    op.create_foreign_key(None, 'forecast_data', 'weather_stations', ['weather_station_id'], ['id'])
    op.drop_column('forecast_data', 'date')
    op.drop_column('forecast_data', 'description')
    op.drop_column('forecast_data', 'temperature')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_data', sa.Column('temperature', sa.FLOAT(), nullable=False))
    op.add_column('forecast_data', sa.Column('description', sa.VARCHAR(), nullable=False))
    op.add_column('forecast_data', sa.Column('date', sa.DATETIME(), nullable=False))
    op.drop_constraint(None, 'forecast_data', type_='foreignkey')
    op.drop_index(op.f('ix_forecast_data_id'), table_name='forecast_data')
    op.drop_column('forecast_data', 'forecast_humidity')
    op.drop_column('forecast_data', 'forecast_temp')
    op.drop_column('forecast_data', 'forecast')
    op.drop_column('forecast_data', 'forecast_date')
    op.drop_column('forecast_data', 'weather_station_id')
    # ### end Alembic commands ###
